/**
 * Whether to scale throttle by battery power level
 *
 * This compensates for voltage drop of the battery over time by attempting to
 * normalize performance across the operating range of the battery. The fixed wing
 * should constantly behave as if it was fully charged with reduced max thrust
 * at lower battery percentages. i.e. if cruise speed is at 0.5 throttle at 100% battery,
 * it will still be 0.5 at 60% battery.
 *
 * @boolean
 * @group TBBV
 */
PARAM_DEFINE_INT32(TBBV_BAT_SCA_EN, 0);

PARAM_DEFINE_INT32(TBBV_SERVO_RE_1, 0);
PARAM_DEFINE_INT32(TBBV_SERVO_RE_2, 0);
PARAM_DEFINE_INT32(TBBV_SERVO_RE_3, 0);
PARAM_DEFINE_INT32(TBBV_SERVO_RE_4, 0);

PARAM_DEFINE_FLOAT(TBBV_KMX, 0.0f);
PARAM_DEFINE_FLOAT(TBBV_KMY, 0.0f);
PARAM_DEFINE_FLOAT(TBBV_KMZ, 0.0f);

PARAM_DEFINE_FLOAT(TBBV_ROLL_P, 0.0f);
PARAM_DEFINE_FLOAT(TBBV_PITCH_P, 0.0f);
PARAM_DEFINE_FLOAT(TBBV_YAW_P, 0.0f);

PARAM_DEFINE_FLOAT(TBBV_ROLL_I, 0.0f);
PARAM_DEFINE_FLOAT(TBBV_PITCH_I, 0.0f);
PARAM_DEFINE_FLOAT(TBBV_YAW_I, 0.0f);

PARAM_DEFINE_FLOAT(TBBV_ROLL_D, 0.0f);
PARAM_DEFINE_FLOAT(TBBV_PITCH_D, 0.0f);
PARAM_DEFINE_FLOAT(TBBV_YAW_D, 0.0f);

PARAM_DEFINE_INT32(TBBV_FEED_FX, 0);
PARAM_DEFINE_INT32(TBBV_FEED_FY, 0);

PARAM_DEFINE_FLOAT(TBBV_ATT_ROLL, 1.0f);
PARAM_DEFINE_FLOAT(TBBV_ATT_PITCH, 1.0f);
PARAM_DEFINE_FLOAT(TBBV_ATT_YAW, 1.0f);

PARAM_DEFINE_FLOAT(TBBV_TRIM_ROLL, 0.0f);
PARAM_DEFINE_FLOAT(TBBV_TRIM_PITCH, 0.0f);

PARAM_DEFINE_FLOAT(TBBV_TOTAL_THRU, 20.0f);
PARAM_DEFINE_FLOAT(TBBV_INT_LIM, 0.01f);

PARAM_DEFINE_INT32(TBBV_SWAP_RY, 0);

PARAM_DEFINE_FLOAT(TBBV_MAX_VEL_Z, 1.0f);
PARAM_DEFINE_FLOAT(TBBV_VEL_Z_P, 0.1f);
PARAM_DEFINE_FLOAT(TBBV_VEL_Z_I, 0.01f);

PARAM_DEFINE_FLOAT(TBBV_WEIGHT, 14.0f);