// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file raspi_.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace { char dummy; }
#endif

#include "raspi_.h"

#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

raspi_::raspi_()
{
    m_value = 0.0;
}

raspi_::~raspi_()
{
}

raspi_::raspi_(const raspi_ &x)
{
    m_value = x.m_value;
}

raspi_::raspi_(raspi_ &&x)
{
    m_value = x.m_value;
}

raspi_& raspi_::operator=(const raspi_ &x)
{
    m_value = x.m_value;
    
    return *this;
}

raspi_& raspi_::operator=(raspi_ &&x)
{
    m_value = x.m_value;
    
    return *this;
}

size_t raspi_::getMaxCdrSerializedSize(size_t current_alignment)
{
    size_t initial_alignment = current_alignment;
            
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    return current_alignment - initial_alignment;
}

size_t raspi_::getCdrSerializedSize(const raspi_& data, size_t current_alignment)
{
    size_t initial_alignment = current_alignment;
            
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    return current_alignment - initial_alignment;
}

void raspi_::serialize(eprosima::fastcdr::Cdr &scdr) const
{
    scdr << m_value;
}

void raspi_::deserialize(eprosima::fastcdr::Cdr &dcdr)
{
    dcdr >> m_value;
}

size_t raspi_::getKeyMaxCdrSerializedSize(size_t current_alignment)
{
	size_t current_align = current_alignment;
            

    return current_align;
}

bool raspi_::isKeyDefined()
{
    return false;
}

void raspi_::serializeKey(eprosima::fastcdr::Cdr &scdr) const
{
	 
}